services:
  ncat:
    image: stephengpope/no-code-architects-toolkit:latest
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ncat.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.ncat.entrypoints=websecure"
      - "traefik.http.routers.ncat.tls=true"
      - "traefik.http.routers.ncat.tls.certresolver=letsencrypt"
      - "traefik.http.services.ncat.loadbalancer.server.port=80"

      - "traefik.http.routers.ncat-api.rule=Host(`api.${APP_DOMAIN}`)"
      - "traefik.http.routers.ncat-api.entrypoints=websecure"
      - "traefik.http.routers.ncat-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.ncat-api.service=ncat-api"
      - "traefik.http.services.ncat-api.loadbalancer.server.port=9090"
    volumes:
      - storage:/var/www/html/storage/app
      - logs:/var/www/html/storage/logs
    restart: unless-stopped
    networks:
      - dokploy-network

volumes:
  storage:
    driver: local
  logs:
    driver: local

networks:
  dokploy-network:
    external: true
